---
title: "build thesis tables"
author: "Bastien-Gregory"
date: "`r Sys.Date()`"
output:
  pdf_document:
    extra_dependencies: ["xcolor", "inputenc", "booktabs",  "makecell",  "multirow", "hhline", "float", "array", "longtable"]
    fig_caption: yes
    number_sections: yes
    toc: no
    latex_engine: pdflatex
    keep_tex: true
header-includes:
  - \usepackage[most]{tcolorbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	warning = FALSE, 
	message = FALSE,
	out.width = "100%",
	fig.fullwidth=TRUE,
	fig.pos = "h")


library(dplyr)
library(kableExtra)

options(dplyr.summarise.inform = FALSE) # remove the override .groups argument

```

Table \ref{tab:generate-immune-table} used \LaTeX describes the specific features of the adaptive response. 

```{r generate-immune-table}
immune_dataset <- readr::read_delim("./tables/innate_vs_adaptive.csv", delim=";", show_col_types = F) %>%
  dplyr::mutate(Feature=stringr::str_to_sentence(Feature), 
                Signification= stringr::str_wrap(Signification, width = 60),
                across(.cols = everything(),kableExtra::linebreak, align="c")) 
immune_dataset[1, 1] <- cell_spec(immune_dataset[1, 1], format= "latex", bold = T) 
immune_dataset[2, 1] <- cell_spec(immune_dataset[2, 1], format= "latex", bold = T) 

immune_dataset %>% 
  kbl(booktabs=T, caption = "The meain features of the adpative response, distinguishing it from the innate response", escape=F) %>%
  kable_styling(latex_options=c("hold_position")) %>%
  row_spec(0,bold=T, align = "c") %>%
  row_spec(1:5, align = "c", hline_after = TRUE) 
```
